/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package content_kasir;

import inc.config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author asus
 */
public class data_buku1 extends javax.swing.JInternalFrame {

    Connection conn= config.conn();
    Statement st;
    ResultSet rs;
    
    
     private void tampil(){
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id");
        model.addColumn("Judul");
        model.addColumn("Noisbn");
        model.addColumn("Penulis");
        model.addColumn("Penerbit");
        model.addColumn("Tahun");
        model.addColumn("Harga Pokok");
        model.addColumn("Harga Jual");
        model.addColumn("PPN");
        model.addColumn("Diskon");
        try{
            String sql= "select * from buku";
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            
            int no=0;
            while(rs.next()){
                no++;
                model.addRow(new Object[]{
                    rs.getString("id_buku"), rs.getString("judul"), rs.getString("noisbn"), rs.getString("penulis"), rs.getString("penerbit"), rs.getString("tahun"), rs.getString("harga_pokok"), rs.getString("harga_jual"), rs.getString("ppn"), rs.getString("diskon")
                });
            }tData.setModel(model);
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void bersih(){
        tId.setText("");
        tJudul.setText("");
        tIsbn.setText("");
        tPenulis.setText("");
        tPenerbit.setText("");
        tTahun.setText("");
        tHarpok.setText("");
        tHarjul.setText("");
        tPpn.setText("");
        tDiskon.setText("");
        tId.setEditable(false);
    }
    /**
     * Creates new form data_buku1
     */
    public data_buku1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        tJudul = new javax.swing.JTextField();
        tIsbn = new javax.swing.JTextField();
        tPenulis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tPenerbit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tTahun = new javax.swing.JTextField();
        tHarpok = new javax.swing.JTextField();
        tHarjul = new javax.swing.JTextField();
        tPpn = new javax.swing.JTextField();
        tDiskon = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        tReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("DATA EGA BOOK'S");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id Buku");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Judul Buku");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No ISBN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Penulis");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        tId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(tId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 274, -1));
        getContentPane().add(tJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 269, 44));
        getContentPane().add(tIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 271, -1));
        getContentPane().add(tPenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 271, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Penerbit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tahun");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Harga Pokok");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Harga Jual");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));
        getContentPane().add(tPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 269, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PPN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Diskon");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));
        getContentPane().add(tTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 228, -1));
        getContentPane().add(tHarpok, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 230, -1));
        getContentPane().add(tHarjul, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 230, -1));
        getContentPane().add(tPpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 230, -1));
        getContentPane().add(tDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 230, -1));

        bSimpan.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, -1, -1));

        bUbah.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        getContentPane().add(bUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 71, -1));

        bHapus.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        getContentPane().add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 71, -1));

        tReset.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        tReset.setText("Reset");
        tReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tResetActionPerformed(evt);
            }
        });
        getContentPane().add(tReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 71, -1));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Id Buku", "Judul Buku", "NO ISBN", "Penulis", "Penerbit", "Tahun", "Harga Pokok", "Harga Jual", "PPN", "Diskon"
            }
        ));
        tData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 830, 100));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cari");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCariKeyPressed(evt);
            }
        });
        getContentPane().add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 220, -1));

        bCari.setText("Cari");
        getContentPane().add(bCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Ega\\foto buku\\2878927b.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        try{
            String sql= "insert into buku value(NULL, '"+tJudul.getText()+"', '"+tIsbn.getText()+"', '"+tPenulis.getText()+"', '"+tPenerbit.getText()+"','"+tTahun.getText()+"', NULL, '"+tHarpok.getText()+"', '"+tHarjul.getText()+"', '"+tPpn.getText()+"', '"+tDiskon.getText()+"')";
            st= conn.createStatement();
            st.executeUpdate(sql);
            
            tampil();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bSimpanActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDataMouseClicked
        int baris= tData.getSelectedRow();
        tId.setText(tData.getModel().getValueAt(baris, 1).toString());
        tJudul.setText(tData.getModel().getValueAt(baris, 2).toString());
        tIsbn.setText(tData.getModel().getValueAt(baris, 3).toString());
        tPenulis.setText(tData.getModel().getValueAt(baris, 4).toString());
        tPenerbit.setText(tData.getModel().getValueAt(baris, 5).toString());
        tTahun.setText(tData.getModel().getValueAt(baris, 6).toString());
        tHarpok.setText(tData.getModel().getValueAt(baris, 7).toString());
        tHarjul.setText(tData.getModel().getValueAt(baris, 8).toString());
        tPpn.setText(tData.getModel().getValueAt(baris, 9).toString());
        tDiskon.setText(tData.getModel().getValueAt(baris,10).toString());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tDataMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        tampil();
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void tResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tResetActionPerformed
        bersih();
        // TODO add your handling code here:
    }//GEN-LAST:event_tResetActionPerformed

    private void tCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyPressed
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id");
        model.addColumn("Judul");
        model.addColumn("Noisbn");
        model.addColumn("Penulis");
        model.addColumn("Penerbit");
        model.addColumn("Tahun");
        model.addColumn("Harga Pokok");
        model.addColumn("Harga Jual");
        model.addColumn("PPN");
        model.addColumn("Diskon");
        try{
            String sql= "select * from buku where id_buku like '%"+tCari.getText()+"%' or judul like '%"+tCari.getText()+"%'";
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            
            int no=0;
            while(rs.next()){
                no++;
                model.addRow(new Object[]{
                    rs.getString("id_buku"), rs.getString("judul"), rs.getString("noisbn"), rs.getString("penulis"), rs.getString("penerbit"), rs.getString("tahun"), rs.getString("harga_pokok"), rs.getString("harga_jual"), rs.getString("ppn"), rs.getString("diskon")
                });
            }tData.setModel(model);
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tCariKeyPressed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        try{
            String sql= "update buku set judul= '"+tJudul.getText()+"', noisbn= '"+tIsbn.getText()+"', penulis= '"+tPenulis.getText()+"', penerbit= '"+tPenerbit.getText()+"', tahun= '"+tTahun.getText()+"', NULL, harga_pokok= '"+tHarpok.getText()+"', harga_jual= '"+tHarjul.getText()+"', ppn= '"+tPpn.getText()+"', diskon= '"+tDiskon.getText()+"'";
            st= conn.createStatement();
            rs= st.executeQuery(sql);
           
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        try{
            String sql= "delete into buku where id_buku'"+tId.getText()+"', ";
            st= conn.createStatement();
            st.executeUpdate(sql);
            
           bersih();
           tampil();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTable tData;
    private javax.swing.JTextField tDiskon;
    private javax.swing.JTextField tHarjul;
    private javax.swing.JTextField tHarpok;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tIsbn;
    private javax.swing.JTextField tJudul;
    private javax.swing.JTextField tPenerbit;
    private javax.swing.JTextField tPenulis;
    private javax.swing.JTextField tPpn;
    private javax.swing.JButton tReset;
    private javax.swing.JTextField tTahun;
    // End of variables declaration//GEN-END:variables
}
