/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package content_kasir;

import inc.config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class data_buku extends javax.swing.JFrame {
    
    Connection conn= config.conn();
    Statement st;
    ResultSet rs;
    
    private void tampil(){
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Judul");
        model.addColumn("Noisbn");
        model.addColumn("Penulis");
        model.addColumn("Penerbit");
        model.addColumn("Tahun");
        model.addColumn("Harga Pokok");
        model.addColumn("Harga Jual");
        model.addColumn("PPN");
        model.addColumn("Diskon");
        try{
            String sql= "select * from buku";
            st= conn.createStatement();
            rs= st.executeQuery(sql);
            
            int no=0;
            while(rs.next()){
                no++;
                model.addRow(new Object[]{
                    rs.getString("id_buku"), rs.getString("judul"), rs.getString("noisbn"), rs.getString("penulis"), rs.getString("penerbit"), rs.getString("tahun"), rs.getString("harga_pokok"), rs.getString("harga_jual"), rs.getString("ppn"), rs.getString("diskon")
                });
            }tData.setModel(model);
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void bersih(){
        tId.setText("");
        tJudul.setText("");
        tIsbn.setText("");
        tPenulis.setText("");
        tPenerbit.setText("");
        tTahun.setText("");
        tHarpok.setText("");
        tHarjul.setText("");
        tPpn.setText("");
        tDiskon.setText("");
        tId.setEditable(false);
    }
    /**
     * Creates new form data_buku
     */
    public data_buku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        tJudul = new javax.swing.JTextField();
        tPenulis = new javax.swing.JTextField();
        tPenerbit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tIsbn = new javax.swing.JTextField();
        tTahun = new javax.swing.JTextField();
        tHarpok = new javax.swing.JTextField();
        tHarjul = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tPpn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tDiskon = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("DATA EGA BOOK'S");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Id Buku");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Judul Buku");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Penulis");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Penerbit");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        tId.setEditable(false);
        jPanel1.add(tId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 328, -1));
        jPanel1.add(tJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 328, 46));

        tPenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPenulisActionPerformed(evt);
            }
        });
        jPanel1.add(tPenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 328, -1));

        tPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPenerbitActionPerformed(evt);
            }
        });
        jPanel1.add(tPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 328, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("No ISBN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Tahun");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Harga Pokok");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Harga Jual");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));
        jPanel1.add(tIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 210, -1));
        jPanel1.add(tTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 210, -1));
        jPanel1.add(tHarpok, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 210, -1));

        tHarjul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHarjulActionPerformed(evt);
            }
        });
        jPanel1.add(tHarjul, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 210, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("PPN");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));
        jPanel1.add(tPpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 133, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Diskon");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        tDiskon.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(tDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 134, -1));

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 79, 30));

        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        jPanel1.add(bUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 79, 30));

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel1.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 79, 30));

        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        jPanel1.add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 79, 30));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Id Buku", "Judul Buku", "Penulis", "Penerbit", "No ISBN", "Tahun", "Harga Pokok", "Harga Jual", "PPN", "Diskon"
            }
        ));
        tData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 847, 100));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Ega\\foto buku\\2878927b.jpg")); // NOI18N
        jLabel1.setText("Cari");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
         try{
            String sql= "insert into buku value(NULL, '"+tJudul.getText()+"', '"+tIsbn.getText()+"', '"+tPenulis.getText()+"', '"+tPenerbit.getText()+"','"+tTahun.getText()+"', NULL, '"+tHarpok.getText()+"', '"+tHarjul.getText()+"', '"+tPpn.getText()+"', '"+tDiskon.getText()+"')";
            st= conn.createStatement();
            st.executeUpdate(sql);
            
            tampil();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bSimpanActionPerformed

    private void tHarjulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHarjulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHarjulActionPerformed

    private void tPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPenulisActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_tPenulisActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        bersih();
        // TODO add your handling code here:
    }//GEN-LAST:event_bResetActionPerformed

    private void tDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDataMouseClicked
        int baris= tData.getSelectedRow();
        
        tId.setText(tData.getModel().getValueAt(baris, 1).toString());
        tJudul.setText(tData.getModel().getValueAt(baris, 2).toString());
        tIsbn.setText(tData.getModel().getValueAt(baris, 3).toString());
        tPenulis.setText(tData.getModel().getValueAt(baris, 4).toString());
        tPenerbit.setText(tData.getModel().getValueAt(baris, 5).toString());
        tTahun.setText(tData.getModel().getValueAt(baris, 6).toString());
        tHarpok.setText(tData.getModel().getValueAt(baris, 7).toString());
        tHarjul.setText(tData.getModel().getValueAt(baris, 8).toString());
        tPpn.setText(tData.getModel().getValueAt(baris, 9).toString());
        tDiskon.setText(tData.getModel().getValueAt(baris, 10).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_tDataMouseClicked

    private void tPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPenerbitActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        try{
            String sql= "insert into buku judul='"+tJudul.getText()+"', noisbn= '"+tIsbn.getText()+"', penulis= '"+tPenulis.getText()+"', penerbit= '"+tPenerbit.getText()+"', tahun= '"+tTahun.getText()+"', harga_pokok'"+tHarpok.getText()+"', harga_jual= '"+tHarjul.getText()+"', ppn= '"+tPpn.getText()+"', diskon= '"+tDiskon.getText()+"'where id_buku'"+tId.getText()+"', ";
            st= conn.createStatement();
            st.executeUpdate(sql);

           tampil();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
         try{
            String sql= "delete into buku where id_buku'"+tId.getText()+"', ";
            st= conn.createStatement();
            st.executeUpdate(sql);

           tampil();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tData;
    private javax.swing.JTextField tDiskon;
    private javax.swing.JTextField tHarjul;
    private javax.swing.JTextField tHarpok;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tIsbn;
    private javax.swing.JTextField tJudul;
    private javax.swing.JTextField tPenerbit;
    private javax.swing.JTextField tPenulis;
    private javax.swing.JTextField tPpn;
    private javax.swing.JTextField tTahun;
    // End of variables declaration//GEN-END:variables
}
